filebeat.prospectors:
- input_type: log
  paths:
    - /var/log/auth.log
  document_type: auth

- input_type: log
  paths:
    - /home/centos/logstash/temporal/FST.txt
  document_type: fst

- input_type: log
  paths:
    - /home/elchivo/gastosMama/gastosMama*.csv
  document_type: mama

output.logstash:
  hosts: ["localhost:5043"]
